# manager-be-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-be
  labels:
    environment: staging   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-be
  template:
    metadata:
      labels:
        environment: staging 
        app: manager-be
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: manager-be
          image: container-registry.zucchetti.com/zucchetti_hospitality/zmenu_next/manager_backend:0.0.3
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            # Accesso a Postgres
            - name: DatabaseSettings__DatabaseHost
              value: zhosp_zmn_manager_staging.hdmng1-pg.service.zdc-1.zcn
            - name: DatabaseSettings__DatabasePort
            - name: DatabaseSettings__DatabaseName
              value: zhosp_zmn_manager_staging
            - name: DatabaseSettings__DatabasePort
              value: "5432"
          volumeMounts:
            - name: backend-config
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: backend-config
          secret:
            secretName: backend-config-secret
            items:
              - key: secret.json
                path: secret.json
